### ISSUE TITLE
Checklist consegna

### ISSUE THREAD

**Issue by jiayihu** [jiayihu/tecweb#12]
Cose da controllare o fare prima della consegna:

- [x] Generare prefix dei browsers come `-webkit-` tramite [autoprefixer](https://github.com/postcss/autoprefixer)
- [x] Settare `production` a TRUE in `config.php` 

## DESIGN

- [x] considerare gli schermi piccoli, ma anche quelli molto grandi
- [x] definire dei punti di rottura
- [x] considerare la stampa:
  - [x] no menù
  - [x] no link (al max evidenziarli/ mettere tra parentesi il link)
  - [x] no colore sfondo
  - [x] meglio togliere colori e immagini in generale di decorazione
  - [x] layout giustificato
  - [x] togliere form “lascia un commento ecc”
  - [x] si breadcump
  - [x] si form lungo con molti dati richiesti
  - [x] usare un font con grazie
  - [x] eliminare eventuali bordi superflui
- [x] ingrandire il font quando gli schermi diventano molto piccoli
- [x] riconoscere e utilizzare convenzioni esterne (es. link sottolineati)
- [x] facilitare la creazione di una mappa mentale all’utente
- [x] marcare i link esplorati di un altro colore
- [x] no scroll orizzontale
- [x] menù orizzontale con max 5 opzioni
- [x] menù verticale con max 10 opzioni
- [x] menù con max 4-5 livelli di profondità
- [x] gerarchie ampie e poco profonde sono facilmente aggiornabili
- [x] menù disponibile in tutte le pagine
- [x] non è detto che un utente arrivi sempre alla home page come prima pagina
- [x] fallimento di un sito → usare tasto back del browser
- [x] primo accesso positivo → poco tempo di caricamento
- [x] non mettere link poco utilizzati  in tutte le pagine (es. accesso amministratore)
- [x] separare la struttura dalla presentazione
- [x] i colori che contengono almeno una di queste coppie sono visti più o meno uguali da tutti gli schermi: 00 33 66 CC FF 99
- [x] layout non giustificato
- [x] font senza grazie

## ACCESSIBILITÀ

- [x] non abbandonare mai l’utente (redirect/pagina 404)
- [x] marcare sempre le parole straniere con <span>
- [x] controllare che i pdf siano accessibili tramite ocr
- [x] fornire sempre un equivalente testuale per ogni media diverso dal testo (tranne per le immagini usate solo a scopo di presentazione → in questo caso preferire CSS3): il testo può essere riprodotto secondo modalità accessibili a quasi tutti gli utenti
- [x] creare documenti che veincolino l’informazione anche se l’utente non può vedere o sentire: fornire informazioni attraverso diversi canali sensoriali alternativi
- [x] creare documenti che non necessitino di un hw specifico
- [x] linguaggio il più chiaro possibile
- [x] usare interlinea ed esposizione per punti
- [x] non usare testo scorrevole, font troppo elaborati, testo sottolineato che non costituisce ancora di un link, testo barrato
- [x] indicare la dimensione dei file in caso di download
- [x] indicare un eventuale cambio lingua (es link esterno)
- [x] corretta definizione delle ancore dei link clicca qui, prosegui ecc
- [x] evitare pop up
- [x] inserire con il tag <img> solo le immagini che effettivamente fanno parte del contenuto
- [x] alt vuoto per immagini di contorno
- [x] immagini di dimensione max 1/2 MB (di più solo per immagini di ambiti specifici es. medico ecc per cui l’utente è disposto ad aspettare un suo eventuale caricamento)
- [x] definizione corretta della tabulazione
- [x] non fare affidamento sui colori
- [x] esplicitare abbreviazioni e acronimi
- [x] i link devono essere facilmente riconoscibili → non utilizzare colori diversi
- [x] screen reader:
  - [x] un utente non deve perdere molto tempo nella lettura di tutte le possibilità offerte dal menù:il testo di un div che utilizza questa classe non è visibile nella pagina ma viene letto dallo screen reader
        .aiuti {
          position: absolute;
          height: 0;
          overflow: hidden;
        }
  - [x] usare attributo tabindex=”numero”
  - [x] non usare accessKey → potrebbero andare in conflitto con altri shortcut
  - [x] usare alternative grafiche al testo es. logo
  - [x] nelle tabelle usare gli attributi:
    - [x] summary → breve descrizione del contenuto della tabella
    - [x] scope → associa le intestazioni alle celle
    - [x] headers → associa le celle alle intestazioni
    - [x] abbr → definire abbreviazioni per le intestazioni
  - [x] form ([guida tecnica](https://www.w3.org/WAI/tutorials/forms/instructions/)):
    - [x] corredare sempre i campi da label (soprattutto per check-box e pulsanti radio
    - [x] raggruppare le voci con outgroup o fieldset
    - [x] utilizzare tabindex e accesskey in modo appropriato nel tag input, textarea e select
    - [x] utilizzare title per fornire informazioni aggiuntive
    - [x] fornire aiuti contestuali
    - [x] rendere gli errori reversibili → indicare sempre cosa è stato sbagliato (aiuto il più particolare possibile, non generico)
## ALTRO
- [x] attenzione ai copyright

## PROVE DA FARE

- [x] riconoscimento link → stampare la pagina, mettere a qualche metro di distanza e chiedere ad una persono di riconoscere tutti i link
- [x] il sito è accessibile anche senza le immagini?
- [x] www.vischeck.com → prova dei colori (utilizzare scheenshot del sito)
- [x] validare tutte le pagine del sito (CSS, HTML e XML)
- [x] usare differenti browser grafici (Firefox, Chrome, IE, Edge)
- [x] usare browser testuali es. LYNX
- [x] usare screen reader
- [x] controllare spelling e grammatica
- [x] invitare persone con disabilità a revisionare i documenti
- [x] rivedere la chiarezza e la semplicità del documento
- [x] FireFox Web Developer Toolbar
- [x] Total Validator → http://www.totalvalidator.com/validator/Validator
- [x] Fangs (FX) → http://sourceforge.net/projects/fangs/
- [x] IE Accessibility Toolbar → http://webaccessibile.org/articoli/la-barra-dell-accessibilita-versione-20/
- [x] Cynthia Says → http://www.contentquality.com/
